server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8000/
          predicates:
            - Path=/auth/**
        - id: main-service
          uri: http://localhost:8001/
          predicates:
            - Path=/main/**
  application:
    name: gateway-service